document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".foot_zi {font-size:12px;font-family:宋体; line-height:180%;}");
document.writeln(".foot_zi a:link{color: #333;text-decoration: none;}");
document.writeln(".foot_zi a:visited{color: #333;text-decoration: none;}");
document.writeln(".foot_zi a:hover{color: #FF7300;text-decoration: underline;}");
document.writeln("");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("");
document.writeln("");
document.writeln("<table width=\"100%\" height=\"30\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><hr width=\"98%\" size=\"2\" noshade=\"noshade\" color=\"0F7CD4\" \/><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"main770 foot_zi\">");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\"><img src=\"http:\/\/meta.alu.cn\/images\/diamond.gif\" align=\"absmiddle\" \/>&nbsp;<a href=\"http:\/\/service.glass.com.cn\/\" target=\"_blank\">建材通服务<\/a><a href=\"\/service\/lyt.htm\" target=\"_blank\"><\/a> | <a ");
document.writeln("      href=\"http:\/\/service.glass.com.cn\/\" target=\"_blank\" ");
document.writeln("      >本网服务<\/a><a ");
document.writeln("      href=\"\/service\/lyt.htm\" target=\"_blank\" ");
document.writeln("      ><\/a> | <a ");
document.writeln("      href=\"http:\/\/service.glass.com.cn\/map.htm\" target=\"_blank\" ");
document.writeln("      >站点导航<\/a> | <a ");
document.writeln("      href=\"http:\/\/service.glass.com.cn\/help.htm\" target=\"_blank\" ");
document.writeln("      >帮助中心<\/a> | <a href=\"http:\/\/www.glass.com.cn\/reg\/jion.html\" ");
document.writeln("      target=\"_blank\">注册会员<\/a><a href=\"\/alucompany\/register.aspx\" ");
document.writeln("      target=\"_blank\"><\/a> | <a ");
document.writeln("      href=\"http:\/\/www.glass.com.cn\/aboutus\/about.htm\" target=\"_blank\" ");
document.writeln("      >关于本网<\/a> | <a ");
document.writeln("      href=\"http:\/\/www.glass.com.cn\/aboutus\/fzlc.htm\" target=\"_blank\" ");
document.writeln("      >发展历程<\/a> | <a ");
document.writeln("      href=\"http:\/\/www.glass.com.cn\/aboutus\/yssm.htm\" target=\"_blank\" ");
document.writeln("      >隐私声明<\/a> | <a ");
document.writeln("      href=\"http:\/\/www.glass.com.cn\/aboutus\/cpyc.htm\" target=\"_blank\" ");
document.writeln("      >诚聘英才<\/a> | <a ");
document.writeln("      href=\"http:\/\/www.glass.com.cn\/aboutus\/lxwm.htm\" target=\"_blank\" ");
document.writeln("      >联系我们<\/a><a ");
document.writeln("      href=\"\/aboutus\/contact.htm\" target=\"_blank\" ");
document.writeln("      ><\/a> | <a href=\"http:\/\/www.glassinchina.com\" ");
document.writeln("      target=\"_blank\">English<\/a><a href=\"http:\/\/en.alu.cn\/\" ");
document.writeln("      target=\"_blank\"><\/a><br \/>");
document.writeln("      <span class=\"footkuang\">中国建材网<\/span>  版权所有 &copy; 1998-2008 咨询热线：0571-<span class=\"footkuang\">89938883<\/span> &nbsp;邮箱:<a href=\"mailto:service@glass.com.cn\" >Service@glass.com.cn<\/a><br \/>");
document.writeln("      <span><strong style=\"color:#FF0000\" ");
document.writeln("      >本站网络实名：中国建材网<\/strong><\/strong>－中国最专业的建材行业信息网站<br \/>");
document.writeln("    <\/strong><\/font><a href=\"http:\/\/www.miibeian.gov.cn\/\" ");
document.writeln("      target=\"_blank\">浙B2-20060159<\/a><\/span><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/js.tongji.yahoo.com.cn\/1\/269\/125\/ystat.js\"><\/script><noscript><a href=\"http:\/\/js.tongji.yahoo.com.cn\"><img src=http:\/\/js.tongji.yahoo.com.cn\/1\/269\/125\/ystat.gif><\/a><\/noscript>");